name: Manual Approval Test Workflow

on:
  workflow_dispatch: # Trigger manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate build
        run: |
          echo "Building your notes project..."
          sleep 3
          echo " Build complete!"


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: menotthakur
      - name: Deploy to production
        run: echo deploying

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Simulate deployment
        run: |
          echo " Deploying your notes project (simulated)..."
          sleep 2
          echo "Deployment complete!"
